name-template: 'VideoSwarm $NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 🚀 Features
    labels: [feature, enhancement]
  - title: 🐛 Fixes
    labels: [bug, fix]
  - title: 🧰 Chores
    labels: [chore, refactor, docs]
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## What’s changed
  $CHANGES

  ## Installation
  - Windows: run the `.exe`
  - Linux: use the `.AppImage` or your distro package if available

  ## Notes
  - See README for system support and known limitations.
